### ISSUE TITLE
I test ttf example,but it's not suppot Chinese 

### ISSUE THREAD

**Issue by zhaokaixs** [libSDL2pp/libSDL2pp#115]
![image](https://user-images.githubusercontent.com/7833585/33704962-74f4e492-db69-11e7-883b-6c5f1c5999dc.png)

**Comment by AMDmi3** [comment]
I bundle very minimal Bitstream Vera font which doesn't have CJK glyphs. Proper font would be too heavy just for the sake of demonstration, while only couple of non-ascii characters are actually needed.

So you'll have to use another font to test Chinese.

However, there seem to be a problem with unicode output on your system, as it should say `«¼½¾» ` instead of 5 squares for the last two lines.

**Comment by zhaokaixs** [comment]
![image](https://user-images.githubusercontent.com/7833585/33714971-e87118f6-db8b-11e7-932e-61bedc0f5599.png)

it's not work well

**Comment by vladimirgamalyan** [comment]
Not sure if sdl2_ttf can properly handle characters above 65535. At least, [TTF_GlyphMetrics](https://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf_38.html) accepts only Uint16 argument for characters/

**Comment by zhaokaixs** [comment]
![image](https://user-images.githubusercontent.com/7833585/33715815-d4052224-db8e-11e7-8aa8-d701b1b23d5d.png)
I change your code like this to test ,it's work,

**Comment by zhaokaixs** [comment]
![image](https://user-images.githubusercontent.com/7833585/33716394-f91e8f76-db90-11e7-8888-0e330f332e3f.png)


I solved the problem,change the cpp file to codepage 936
