### ISSUE TITLE
Problem in VS Code.

### ISSUE THREAD

**Issue by chinu8005** [libSDL2pp/libSDL2pp#130]
when I type the code in VS code this shows up in the terminal
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingw32.a(main.o):(.text.startup+0xc0): undefined reference to `WinMain@16'     
![Screenshot 2020-12-05 190432](https://user-images.githubusercontent.com/75530713/101244474-c9489d00-372c-11eb-9480-ffb33bfee325.png)
 Help it please.

**Comment by digumx** [comment]
I faced a similar issue at some point, could you try changing the signature of main to include the arguments? That is, try with `int main(int argc, char** argv)`.

I believe SDL does something wierd on windows by macroing out the main method definition and implementing it's own main that calls the user defined main method. My wild guess is that the macro they use is the definition of main with the arguments included, and since you do not have the arguments included the macro magic is failing.

**Comment by AMDmi3** [comment]
I don't see how this relates to libSDL2pp - you don't include its headers or link its libraries. You should probably start with mingw32 documentation and my guess is that you should define `WinMain()` instead of `main()` as the error says. SDL does provide machinery which allows you to use `main()` on all platforms, but since you don't use it directly or via libSDL2pp it doesn't work here.
