### ISSUE TITLE
Problems compiling with Mingw-w64

### ISSUE THREAD

**Issue by qzole** [libSDL2pp/libSDL2pp#66]
Want to start a project with SDL2 with c++, and found this wrapper (awesome work on it btw), but I found problems when I tried to compile it in a Mingw-w64 environment (using MSYS2).
The main problem is that the linker says that there is undefined reference for the WinMain function (special entry point for Windows GUI programs to my best knowledge). This is defined in SDL2_main lib (part of core SDL2), it just parses the program arguments and passes them onto SDL_main function.
This same problem appears when I try to build the tutorials.

Simply linking to SDL2 works, using pkg-config like so:
```
find_package(PkgConfig REQUIRED)
pkg_search_module(SDL2 REQUIRED sdl2)
include_directories(${SDL2_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} ${SDL2_LIBRARIES})
```

It seems that the current build system in SDL2pp leaves SDL2_main out altogether. As I checked what libraries the two methods find (the one in libSDL2pp and the one mentioned above).
libSDL2pp way only finds and uses `libSDL2.dll.a` with full path. While the above mentioned finds and uses `mingw32 SDL2main SDL2`.

Linking with SDL2main gives a new error that SDL_main is undefined, this is because the signature of the main functions in SDL2pp project are missing the standard `int` and `char**` parameters. Changing that fixes the build.

Using this all together my current workaround is to link SDL2pp and SDL2 too (the libraries that pkg-config gives).
It seems that using pkg-config, or using a more complete findsdl2.cmake would help this problem (there are several findsdl2.cmake floating on the web, I prefer the pkg-config way). The `main` functions' signature should be fixed too. I would gladly contribute and create a pull request if there is an agreement how this problem should be mitigated (or if it's a problem at all in your view).

As a last note, I saw that there is an MSVC specific part in the root CMakeLists.txt, I haven't tested it with Visual C++ yet, and now comes the realization if it's a supported compiler, then relying on pkg-config is probably not an option...

Sorry if I wasn't all coherent, if something is not clear or more info is needed, then ask, I'm eager to help with this issue. In the meantime I'll try to compile with Visual C++.

**Comment by ooxi** [comment]
As far as I know SDL does not provide an `SDL_main` function but declares an macro replacing `main` with `SDL_main` iff `SDL_MAIN_NEEDED` or `SDL_MAIN_AVAILABLE` are defined. Thus it should be sufficient to include `SDL2/SDL2.h` in your main source file with C linkage

````C
#ifdef __cplusplus
extern "C"
#endif
int main(int argc, char *argv[])
{
    ...
}
````

If that doesn't help, maybe you could upload a minimal example so we can reproduce the error?

**Comment by AMDmi3** [comment]
Please try sdlmain branch. If it works for you, I'll merge it.

**Comment by qzole** [comment]
Tried to compile, it still throwed undefined WinMain function, but didn't have time to check why. Will look into it tonight, after work.

**Comment by AMDmi3** [comment]
Try adding -DCMAKE_EXE_LINKER_FLAGS="-lmingw32" to cmake arguments.
I'm currently playing with mingw build in appveyor, will elaborate on this more after a while.

**Comment by AMDmi3** [comment]
Ok, now lemme elaborate on windows support a bit more.

Unfortunately I can't call it official yet (either msvc or mingw build). Honestly, windows support is a horrible utter pain: I've spent about 150 appveyor builds and several weeks to build anythong at all (I've experimented on both libSDL2pp and https://github.com/AMDmi3/hoverboard-sdl which uses libSDL2pp). Apart from some real bugs such as missing SDLmain support, a couple of missing includes and general windows weirdness I've had to overcome (mainly braindead cmd issues) there are some major problems I could not solve properly yet:
- MSVC: upstream SDL2 binary packages are built with MSVC 2012, but we need MSVC 2015 for C++11 support. MSVC 2012/2015 are not binary compatible (see comment in .appveyor.yml), so we can't build usable library or executables with VC compiler unless we rebuild whole SDL2, SDL2_{mixer,image,ttf} and probably all their respective dependencies (flac, freetype, jpeg, modplug, ogg, png, tiff, vorbis, webp, smpeg, zlib). Unbelievably, windows still has no package repository to fetch these from or source based ports system to build these easily
- MINGW: the build requires adding -lmingw32 to link flags. Yes, it's provided by pkg-config (and SDL docs do recommend to use pkg-config), but I'd strongly prefer to not use it as it's not cross-platform enough (e.g. not usable for msvc builds) and is inferior to what CMake does itself (e.g. library detection and use of global library paths instead of ```-Llibpath -llibname``` errorprone clumsiness). Generally, I'd prefer to keep platform-specific code such as this -lmingw32 away from my repos - it should highly likely be handled by cmake or mingw itself instead, but in libSDL2pp I also have to stick with SDL2 upstream behavior, which adds it explicitly for some reason, so in the end I think I'll have to add -lmingw32 for mingw builds specifically. Still I'd really like to know why it is needed.

**Comment by qzole** [comment]
Thanks for all the effort you put into this problem. I tested building SDL2pp, and it works with the `-lmingw32` flag.
I tried to search for the reason, why this flag is needed for mingw builds and had no luck finding an answer. It seems everyone accepted that this is needed, but no one cared why?! I'll ask on the SDL2 development forums, maybe someone there knows the reason. It just seems weird especially what happens without the flag:

Without using the flag, thus **not** linking with the mingw32 lib, here is the undefined reference I get:
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
```
Notice that it comes from libmingw32.a!
This same error happens if the order of the flags are switched (so SDLmain comes before mingw32: `-lSDLmain -lmingw32`).
I feel like I'm still in the dark, but I'll try to dig to the bottom of this.

**Comment by vladimirgamalian** [comment]
I'v tried to build SDL2 and satelites with VS2015: https://github.com/vladimirgamalian/sdl2_msvc_builds. Maybe it can help to resolve the SDL2pp MSVC build issue. I believe, we do not need to recompile dependencies (flac, freetype, jpeg, modplug, ogg, png, tiff, vorbis, webp, smpeg, zlib), cause it come as dynamic libraries.

**Comment by AMDmi3** [comment]
I've added -lmingw32 to the link flags, I don't see any other solution for now. Please test.

**Comment by qzole** [comment]
Tested it, and it works, thanks!

I also did some research and I think I know the reason for this behaviour, but I'm not sure what would be a good clean solution for it.

The reason is that when linking with gcc the order of libraries matters. When gcc links a static library it will only use the object files from it which resolves **previously** undefined symbols. In this case when it links SDLmain the `main` symbol is not undefined so it won't include the only object file from the library in the linking process. How does it become undefined then? Well the mingw32 lib is the runtime library of MinGW's gcc and it gets linked automatically, but only **after** the user defined libraries. This library contains the  `crt0_c` object which contains the entry point for the program, which references the `main` function\*, so now it becomes an undefined symbol, but it won't get resolved since SDLmain was already thrown away... That is why the solution is to link mingw32 manually before SDLmain, just so it can generate the undefined symbol, so when SDLmain is linked its object file which resolves it will be included in the linking process.

SDLmain is used to abstract away the different "main" entry points on the different platforms. On Windows there are 4: `main` and `WinMain`, both with narrow and wide character parameters, see http://stackoverflow.com/a/13872211/5114859 

On linux gcc is used, but it's not a problem because SDLmain is not needed there.
On Windows with Visual Studio, I think this isn't problem (haven't found anything like this when searching), maybe the linker works differently.

One solution would be that the main function is not put in a static library, but in an object file. When object files are linked directly, they are actually linked! This is the reason there is no undefined symbol error for `main` when compiling a simple program. This raises the problem of how can this object file be distributed and found by the build process?
Another solution would be (which boils down to the same as above), is to put the definitions of these main functions in a header file, so when a client application who uses SDL2 includes them it will be compiled into one of the object files of the client. This raises the problem that it could break working SDL2 projects (it would be easy to fix though, I think), or the main functions would be defined multiple times (right now including `SDL.h` includes `SDLmain.h` too). Maybe it would complicate building for other platforms like Android.
Another solution would be to convince the developers of gcc to not throw out object files when linking static libraries. Ok this was just a joke, it would open a whole can of worms since now those new object files can generate undefined symbols of their own, so previously working builds could be broken.

Sorry, that I was so slow with the reply.

\*: If MinGW doesn't find `main`, it'll search for `WinMain`, and if it doesn't find that, it'll emit the error that `WinMain` is not found, even though defining `main` would be enough.

**Comment by AMDmi3** [comment]
Wow, thank you for this thorough research! It's a lot more clear to me, however I still don't see a  cleaner solution than we already have. Especially given that SDL itself does the same and I want to be compatible, it will likely have to stay that way.

In general though, I see two causes of this problem:
- SDL uses this main() replacement hack. Though the goal (the same code for all platforms) is worthwile, the means are, as it can be seen, ugly and error prone.
- gcc linker could be more clever. I've stepped into it multiple times, when I could not link some legacy code because libraries were listed before object files, or ran into cyclic dependencies between static libraries.

If either is fixed, the hack could be removed. Anyway, I'm glad to know that it works.

**Comment by rthickling** [comment]
I believe I have this problem now in 2021!
The `-lmingw32` hack doesn't seem to work though...
The error is:
```shell
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_w.o): in function `wmain':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_w.c:23: undefined reference to `wWinMain'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Clownacy** [comment]
I know that I'm a year late, but the reason that wWinMain is undefined is because SDL2 doesn't provide wWinMain - only regular WinMain. I imagine you'd have to disable unicode mode to avoid that error.

**Comment by AMDmi3** [comment]
> you'd have to disable unicode mode

I have no idea how to do that. Patches are welcome.

**Comment by l-t-m-f** [comment]
> I believe I have this problem now in 2021! The `-lmingw32` hack doesn't seem to work though... The error is:
> 
> ```shell
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_w.o): in function `wmain':
> C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_w.c:23: undefined reference to `wWinMain'
> collect2.exe: error: ld returned 1 exit status
> ```

I add exactly same issue as you  !!! You need to remove -municode and link libraries
"-lmingw32",  "-lSDL2main",   "-lSDL2", ...

**Comment by moekhalil** [comment]
> > I believe I have this problem now in 2021! The `-lmingw32` hack doesn't seem to work though... The error is:
> > ```shell
> > C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_w.o): in function `wmain':
> > C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_w.c:23: undefined reference to `wWinMain'
> > collect2.exe: error: ld returned 1 exit status
> > ```
> 
> I add exactly same issue as you recently. You need to remove -municode and link -lmingw32 before -lSDL2main, -lSDL2, ...

Thank you from 2024! I spent hours debugging this 😒, and then just as I was giving up I found your post and decided to put -lmingw32 at the VERY BEGGINING lol and it worked!
